File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:33:07
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:33:12
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:33:17
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:33:22
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:33:27
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:33:33
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:33:38
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:35:13
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:35:18
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:35:23
File "/home/pi/Python/SetCurtain.py", line 27, in disable_motor|Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)|2019-12-21 20:35:28
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:18
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:23
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:28
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:33
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:38
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:43
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:48
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:53
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:56:58
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:57:03
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:57:09
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:57:14
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:57:19
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:57:24
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:57:29
File "/home/pi/Python/GPIOUtility.py", line 43, in setup_GPIO|name 'DIRECTION_PIN' is not defined|2019-12-21 20:57:34
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:57:36
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:57:42
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:57:47
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:57:52
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:57:57
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:58:03
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:58:07
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:58:12
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:58:18
File "Main.py", line 130, in main|name 'threading' is not defined|2019-12-21 20:58:23
File "Main.py", line 105, in connect_to_DB|local variable 'cursor' referenced before assignment|2019-12-21 21:13:04
File "Main.py", line 105, in connect_to_DB|local variable 'cursor' referenced before assignment|2019-12-21 21:13:09
File "Main.py", line 105, in connect_to_DB|local variable 'cursor' referenced before assignment|2019-12-21 21:13:15
File "Main.py", line 105, in connect_to_DB|local variable 'cursor' referenced before assignment|2019-12-21 21:13:20
